#!/bin/bash

mkdir ~/Pictures
mkdir ~/.cache
touch ~/.cache/.pics

mkdir -p ~/.config/WallFade
touch .config/WallFade/TermInfo
touch .config/WallFade/TermColors

sudo cp ./WallFade /usr/bin/WallFade
sudo cp ./getTermInfo /usr/bin/getTermInfo
sudo cp ./updateTermInfo /usr/bin/updateTermInfo
